services:
  db:
    container_name: netflix_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: netflix_user
      POSTGRES_PASSWORD: netflix
    volumes:
      - ./scripts/docker/init.sql:/docker-entrypoint-initdb.d/00-init.sql
    ports:
      - "5432:5432"
