package org.example.ui.tui;

public enum ConsoleAppScreen {
    STARTING,
    LOGIN,
    REGISTER,
    PROFILE_PICKER,
    CREATE_PROFILE,
    MAIN_MENU,
    LIST_MOVIES,
    LIST_SERIES,
    SEARCH_MOVIES,
    SEARCH_SERIES,
    LIST_MOVIES_BY_CATEGORY,
    LIST_SERIES_BY_CATEGORY,
    EDIT_PROFILE,
    DELETE_PROFILE,
}
